server:
  port: 8086


spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/socialnet
    username: root
    password: root

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db\changelog\socialnet_changelog.xml


logging:
  level:
    org.hibernate:
      SQL: info

aws:
  bucket-name: socialnet-bucket
  accessKeyId: AKIAV3IS4ZIFYKNKL4MX
  secretAccessKey: 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
  region: EU_NORTH_1
