server:
  port: 8086

client:
  local: http://localhost:8080
  remote: http://217.107.219.242:8080

spring:
  profiles:
    active: '@spring.profiles.active@'

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST}:${POSTGRESQL_PORT}/socialnet
    username: root
    password: root

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none

    open-in-view: false
    show-sql: true

  liquibase:
    enabled: true
    change-log: classpath:db\changelog\socialnet_changelog.xml

  servlet:
    multipart:
      max-file-size=5MB
      max-request-size=5MB


  kafka:
    bootstrap-servers:  ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092}

jwt:
  secret: 6E76BC89F358872832CC3DBEC8A95
  lifetime: 12h

logging:
  level:
    org.hibernate:
      SQL: info

logger:
  path: logs
  expired: PT168H
  console:
    thresholdFilter: '@logger.console.thresholdFilter@'

aws:
  image-bucket-name: socialnet-bucket
  access-key-id: ${AWS_ACCESS_KEY_ID}
  secret-access-key: ${AWS_SECRET_KEY}
  region: eu-north-1
  max-image-file-size: 5242880
  photo-url-prefix: https://socialnet-bucket.s3.eu-north-1.amazonaws.com/
  default-photo-url: https://socialnet-bucket.s3.eu-north-1.amazonaws.com/profile_photo_default.jpg
  log-bucket-name: socialnet-logs
  max-log-file-size: 5242880
  log-url-prefix: https://socialnet-logs.s3.eu-north-1.amazonaws.com/

email:
  project-email: ${PROJECT_EMAIL}
  project-email-password: ${PROJECT_EMAIL_PASSWORD}
  smtp-auth: true
  smtp-starttls-enable: true
  smtp-host: smtp.gmail.com
  smtp-port: 587
  smtp-ssl-trust: true
  recovery-base-url: http://217.107.219.242:8080/
  recovery-email-blueprint: emailBlueprint.html

vk:
  key: ${VK_SERVICE_KEY:service-key}


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true

# swagger-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui

schedule:
  currency-download: "0 5 0 * * *"
  weather-update: "0 */10 * * * *"
  remove-deleted-posts-in: "PT1H"

openweathermap:
  api_key: ${OPENWEATHERMAP_API_KEY:api-key}

app:
  kafka:
    kafkaMessageTopic: message-topic
    kafkaMessageGroupId: kafka-message-group-id

default-deleted-user-id: 0