server:
  port: 8083

db:
  schema: socialnet

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:54321/socialnet?currentSchema=${db.schema}
    username: root
    password: root

  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

    open-in-view: false
    show-sql: true
    properties:
      hibernate.default_schema: ${db.schema}

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db\changelog\socialnet_changelog.xml
    default-schema: ${db.schema}

logging:
  level:
    org.hibernate:
      SQL: info