version: "3"

services:

  postgresql:
    image: postgres:latest
    container_name: postgresql
    hostname: postgresql
    restart: on-failure
    ports:
      - 54321:5432
    environment:
      - POSTGRES_DB=socialnet
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root