insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (false, false, true, false, false, false, true);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (true, true, false, false, false, false, true);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (true, false, false, false, true, true, false);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (false, false, true, false, false, false, true);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (false, true, true, true, false, false, true);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (true, false, true, false, false, false, true);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (false, false, true, false, false, false, true);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (true, false, false, false, true, true, false);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (true, true, true, false, false, false, true);
insert into person_settings (comment_comment, friend_birthday, friend_request, post_like, message, post_comment, post) values (true, false, false, false, true, false, false);

insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Prent', 'Jendrys', 'pjendrys0@ibm.com', '+7-245-869-0603', '2023-06-23 07:38:38', '2003/11/30', 'Lugovoy', 'Kazakhstan', null, '2022-12-12 23:57:19', true, false, false, 1, 'kF2(r|N<BM)+&h', 'ALL', false);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Jonie', 'Twallin', 'jtwallin1@sphinn.com', '+1-480-875-8042', '2023-06-04 22:49:03', '1990/03/06', 'Scottsdale', 'United States', null, '2022-11-22 02:51:37', false, false, false, 2, 'pJ0*q_rI', 'ALL', false);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Vonni', 'Tipple', 'vtipple2@bigcartel.com', '+1-516-566-1568', '2023-04-04 16:04:19', '1990/03/06', 'Great Neck', 'United States', null, '2023-02-12 12:50:13', true, false, false, 3, 'kN0=.E#}3sG&Mv', 'ALL', false);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Evangelia', 'Baverstock', 'ebaverstock3@auda.org.au', '+81-429-165-9027', '2023-06-18 18:52:35', '1986/08/08', 'New York', 'United States', null, '2022-10-20 23:58:27', false, false, false, 4, 'oH0<Pd*@EKl&2Z', 'ALL', false);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Davine', 'Paggitt', 'dpaggitt4@springer.com', '+970-693-864-0184', '2023-01-08 07:11:04', '1979/03/04', 'Ḩuwwārah', 'Palestinian Territory', null, '2023-01-19 22:40:00', true, false, false, 5, 'hX8`a9R|*G04Ml!5', 'ALL', true);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Johna', 'Dunbar', 'jdunbar5@angelfire.com', '+84-687-942-5742', '2023-05-25 04:50:31', '2001/02/27', 'Vĩnh Thuận', 'Vietnam', null, '2023-06-19 08:53:46', true, true, false, 6, 'oZ5*Hb+c<X\8$Rk3', 'ALL', false);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Milicent', 'Tarren', 'mtarren6@epa.gov', '+86-735-511-9370', '2023-03-04 17:26:13', '1999/04/21', 'Caiyuan', 'China', null, '2023-08-11 17:40:05', false, false, true, 7, 'bE6{QaEY&C?<', 'ALL', false);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Aubrie', 'Lethebridge', 'alethebridge7@patch.com', '+850-145-248-7203', '2023-05-05 19:48:55', '1965/04/01', 'Los Angeles', 'United States', null, '2023-08-26 08:29:11', true, false, false, 8, 'wW5%#cz`0h($}', 'ALL', true);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Minni', 'Baptie', 'mbaptie8@liveinternet.ru', '+992-563-140-0686', '2023-08-06 04:25:41', '1997/06/07', 'Dŭstí', 'Tajikistan', null, '2023-09-07 10:18:28', true, false, false, 9, 'aU4&>,8C}', 'ALL', false);
insert into persons (first_name, last_name, e_mail, phone, reg_date, birth_date, city, country, deleted_time, last_online_time, is_approved, is_blocked, is_deleted, person_settings_id, password, message_permissions, online_status) values ('Gaile', 'Rizzotto', 'grizzotto9@census.gov', '+52-713-405-0877', '2023-10-05 23:50:45', '2005/11/10', 'Lazaro Cardenas', 'Mexico', null, '2022-10-23 23:25:50', true, false, false, 10, 'iN8*iUiG8!wcO4qJ', 'ALL', false);

insert into friendships (sent_time, status_name, dst_person_id, src_person_id) values ('2023-09-22 22:01:13', 'BLOCKED', 2, 1);


